name: Daily Auto Commit

on:
  schedule:
    - cron: '0 0-5 * * *'  # Every hour from midnight to 5 AM UTC
    - cron: '0 6-23/6 * * *' # Every 6 hours from 6 AM to 11 PM UTC

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Choose your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run auto commit script
        run: |
          python auto_commit.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
