name: Auto commit

on:
  push:
    branches:
      - master
      
  schedule:
    - cron: "*/15 * * * *" # Adjust as needed

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Set up debugging
        run: echo "::debug::Ref = ${{ github.ref }}"

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false # Do not use the workflow’s token for `git` commands.
          fetch-depth: 0             # Fetch all history to ensure complete git info.

      - name: Configure Git
        run: |
          git config --local user.email "gotfgodz@gmail.com"
          git config --local user.name "gotf godz"

      - name: Pull latest changes from remote
        run: |
          git fetch origin master     # Fetch changes from remote
          git reset --soft origin/master  # Soft reset to align with remote without overwriting changes
          git pull --ff-only origin master || echo "No new changes to pull" # Fast-forward pull to avoid conflicts

      - name: Modify last update timestamp
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED

      - name: Stage changes
        run: |
          git add LAST_UPDATED

      - name: Commit changes if needed
        run: |
          # Only commit if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            messages=("feat: updated timestamp" "fix: modified LAST_UPDATED" "chore: timestamp update")
            rand=$((RANDOM % ${#messages[@]}))
            git commit -m "${messages[$rand]}"
          else
            echo "No changes to commit"
          fi

      - name: Push changes to GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
